language: node_js

env:
  SSH_USER: root
  APP_PATH: /root/coffee-print/coffee-print-docker
  DEPLOY_PATH: /root/coffee-print/coffee-print-server
  DOCKER_APP_PATH: app
  PATH_UPLOADS: uploads
  SERVICE_NAME: coffee-print

sudo: false

git:
  depth: false

branches:
  only:
    - master

before_install:
  - openssl aes-256-cbc -K $encrypted_7a73c6c32b3d_key -iv $encrypted_7a73c6c32b3d_iv -in ./.travis/id_rsa.enc -out ./.travis/id_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./.travis/id_rsa
  - echo -e "Host $SSH_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
  - ssh-add ./.travis/id_rsa

install: true

script:
  - echo "npm test temporarily disabled"

deploy:
  provider: script
  skip_cleanup: true
  script: bash -c '
    ssh root@$SSH_HOST "find /root/coffee-print/coffee-print-server
        -not -path \"/root/coffee-print/coffee-print-server\"
        -not -path \"/root/coffee-print/coffee-print-server/uploads*\" -delete"'
  on:
    branch: master
