language: node_js

env:
  SSH_USER: root
  APP_PATH: /root/coffee-print/coffee-print-docker
  DELPOY_PATH: /root/coffee-print/coffee-print-server

sudo: false

git:
  depth: false

branches:
  only:
    - master

before_install:
  - openssl aes-256-cbc -K $encrypted_7a73c6c32b3d_key -iv $encrypted_7a73c6c32b3d_iv -in ./.travis/id_rsa.enc -out ./.travis/id_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./.travis/id_rsa
  - echo -e "Host $SSH_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
  - ssh-add ./.travis/id_rsa

install: false

script:
  - echo "npm test temporarily disabled"

deploy:
  provider: script
  skip_cleanup: true
  script: bash -c '
    ssh root@$SSH_HOST "systemctl stop coffee-print && rm -rf $DELPOY_PATH"
    && rsync --recursive ./* $SSH_USER@$SSH_HOST:$DELPOY_PATH/
    && ssh root@$SSH_HOST "cd $APP_PATH && docker-compose run app bash -c \"npm install && npx sequelize db:migrate \" && systemctl start coffee-print"'
  on:
    branch: master
